# Adapter configurations
adapters:
  openai:
    type: openai
    enabled: true
    config_file: openai.yaml
    priority: 2
    
  qwen_text:
    type: qwen_text
    enabled: true
    config_file: qwen_text.yaml
    priority: 1  # Prefer local
    
  qwen_vision:
    type: qwen_vision
    enabled: true
    config_file: qwen_vision.yaml
    priority: 1
    
  anthropic:
    type: anthropic
    enabled: true
    config_file: anthropic.yaml
    priority: 3