# Server configuration
server:
  host: 0.0.0.0
  port: 8000
  workers: 4
  
# API settings
api:
  prefix: /v1
  title: LLM Router API
  version: 1.0.0
  
# Logging
logging:
  level: INFO
  format: json
  file: logs/router.log
  
# CORS
cors:
  enabled: true
  origins: ["*"]
  methods: ["*"]
  headers: ["*"]

# Rate limiting
rate_limit:
  enabled: false
  requests_per_minute: 100