# OpenAI GPT-4o-mini model configuration
name: gpt-4o-mini
provider: openai
model_id: gpt-4o-mini

# Model capabilities
capabilities:
  chat: true
  vision: true
  function_calling: true
  streaming: true
  embeddings: false

# Model parameters
temperature: 0.7
max_tokens: 4096
top_p: 1.0
frequency_penalty: 0.0
presence_penalty: 0.0

# API settings
timeout: 60
max_retries: 2

# Context window
context_window: 128000

# Cost information (per 1M tokens)
cost:
  input: 0.15  # USD per 1M input tokens
  output: 0.60  # USD per 1M output tokens

# Model description
description: "OpenAI's fast and cost-effective small model, supports vision"
use_cases: ["quick_responses", "vision_tasks", "cost_effective"]