# Provider-level adapter configurations
adapters:
  openai:
    type: openai
    enabled: true
    config_file: provider_openai.yaml
    priority: 2
    models_dir: "models/openai"
    
  qwen:
    type: qwen
    enabled: true
    config_file: provider_qwen.yaml
    priority: 1  # Prefer local
    models_dir: "models/qwen"
    
  anthropic:
    type: anthropic
    enabled: true
    config_file: provider_anthropic.yaml
    priority: 3
    models_dir: "models/anthropic"