# Routing rules configuration - Based on actual model configs in configs/models/
rules:
  # Explicit model mappings - ONLY models that have config files
  explicit_models:
    # OpenAI models (configs/models/openai/)
    - models: [gpt-4o-mini, text-embedding-3-large]
      adapter: openai
    
    # Anthropic models (configs/models/anthropic/)
    - models: [claude-3-5-sonnet-20241022]
      adapter: anthropic
    
    # Qwen models (configs/models/qwen/)
    - models: [Qwen3-14B-Instruct-bnb-4bit, Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit, Qwen3-embedding-0.6B]
      adapter: qwen
  
  # Content-based routing - using only available models
  chat_default: gpt-4o-mini                    # Chat model we have config for
  vision_default: gpt-4o-mini       # Vision model we have config for
  embedding_default: text-embedding-3-large                         # Embedding model we have config for
